name: Test cache

on:
  push:
    branch:
      - 'main'

jobs:
  build:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Set up Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: 'yarn'

      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}

      - name: Set up Cocoapods cache
        uses: actions/cache@v3
        id: cocoapods-cache
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install dependencies
        if: steps.node_modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Install pod dependencies
        if: steps.cocoapods-cache.outputs.cache-hit != 'true'
        run: |
          cd ios && pod install
